#!/usr/bin/env python3

import sys

def is_int(string):
    try:
        int(string)
        return True
    except ValueError:
        return False

def is_error_arg(argv):
    if (len(argv) != 2):
        return True
    file_content = get_file_content(argv[1])
    machine_list = get_machines(file_content)
    if (len(machine_list) != 2):
        return True
    if (len(machine_list[0]) != 4 or len(machine_list[1]) != 4):
        return True
    if (len(machine_list[0][0]) != 3 and len(machine_list[1][0]) != 3):
        return True
    if (is_int(machine_list[0][1]) == False or is_int(machine_list[0][2]) == False or is_int(machine_list[0][3]) == False):
        return True
    if (is_int(machine_list[1][1]) == False or is_int(machine_list[1][2]) == False or is_int(machine_list[1][3]) == False):
        return True
    return False

def get_file_content(file_name):
    f = open(file_name, "r")
    file_content = f.read()
    return file_content

def get_machines(file_content):
    machine_list = file_content.splitlines()
    result = [machine_list[0].split(), machine_list[1].split()]
    return result

def get_moyenne_panne(machine):
    return int(machine[1]) * (int(machine[2]) + int(machine[3]))

def find_better(machine1, machine2):
    if (get_moyenne_panne(machine1) > get_moyenne_panne(machine2)):
        return machine2[0]
    else:
        return machine1[0]

def main(argv):
    if (is_error_arg(argv) == True):
        exit(84)
    else :
        file_content = get_file_content(argv[1])
        machine_list = get_machines(file_content)
        print(find_better(machine_list[0], machine_list[1]))


main(sys.argv)
